### ISSUE TITLE
Hook ordering is wrong when a hook is flagged

### ISSUE THREAD

**Issue by lukespragg** [OxideMod/OxidePatcher#100]
![c5c673e05786b035ff1f506f7f38adb8](https://cloud.githubusercontent.com/assets/671337/10798256/2c647cde-7d7d-11e5-8d90-9a6d048b0886.png)

![2c93230ce5a5df63a22a4ea5a70b4b70](https://cloud.githubusercontent.com/assets/671337/10798255/2c5d3cb2-7d7d-11e5-81c8-720b1c08773a.png)

**Comment by HellUnit** [comment]
Might have to do with the fact that it's in a subfolder. I used a really old *.opj file and the hooks stay in the same order even after opening and closing the file. I'll try it with a more recent version.

**Comment by Mughisi** [comment]
The issue was caused because the project file only contains a single folder which caused the hooks in that folder to not be sorted.
This was fixed with ef5c95ede24d87005d63be8751cabd47170eb293
