### ISSUE TITLE
Argument String

### ISSUE THREAD

**Issue by serg1980serg** [OxideMod/OxidePatcher#112]
How to use "Argument String"
![image](https://cloud.githubusercontent.com/assets/14067321/11800340/d439e036-a305-11e5-9d81-0b29cc37203e.png)

**Comment by lukespragg** [comment]
I'd recommend taking a look at some of the existing hooks for games we support.

The "a#" are from the method's arguments and the "l#" are from the variables in the code from the method you are hooking. You can also pass "this" which is the Type Name. Fields and such are also supported, ex. "this.sender", "a0.player", etc, but those will vary per game.
