### ISSUE TITLE
Removing a hook doesn't update category

### ISSUE THREAD

**Issue by neico** [OxideMod/OxidePatcher#114]
Looking at the code in PatcherForm.cs it seems obvious:
"RemoveHook" isn't handling the change of hook states like "UpdateHook" does.
As there might be other areas where an TreeNode Update might be needed I'd probably move that logic in a seperate function and call it on at least said functions.

An easy workaround is to reload the project as the Initialisation code also handles it (duplicated code anyone?)

**Comment by Mughisi** [comment]
Fixed in 379cd166e221342cea99cddc068112b5ce1f95ba
