### ISSUE TITLE
Hooks fail to apply when using console mode

### ISSUE THREAD

**Issue by neico** [OxideMod/OxidePatcher#115]
Seems like you guys are breaking the Patcher more frequently lately...

Maybe the patcher needs some CI support to spot those earlier, and use feature branches to avoid disrupting normal workflow (since the snapshots repo doesn't seem to have a commit history where you can fallback to the previous version...)

```
Failed to apply hook CanBuild
System.NullReferenceException: Der Objektverweis wurde nicht auf eine Objektinstanz festgelegt.
   bei OxidePatcher.Hooks.Simple.GetFieldOrProperty(ILWeaver weaver, MethodDefinition originalMethod, TypeDefinition currentArg, String[] target)
   bei OxidePatcher.Hooks.Simple.PushArgsArray(MethodDefinition method, ILWeaver weaver, VariableDefinition& argsvar)
   bei OxidePatcher.Hooks.Simple.ApplyPatch(MethodDefinition original, ILWeaver weaver, AssemblyDefinition oxideassembly, Boolean console)
   bei OxidePatcher.Patching.Patcher.Patch(Boolean console)
```

**Comment by lukespragg** [comment]
I can't reproduce that error @neico. I've been using the patcher changes for awhile now without issue. Are you sure you are updated?

**Comment by neico** [comment]
Strange, my start script always fetches the most recent version from the snapshot repo so it should be up2date...

Need to take a closer look later on...

**Comment by neico** [comment]
Here's the log of the entire patch process, I fail to see a pattern yet as some seem to be unaffected and it's not being limited to SImple but also to Modify Hooks

http://puu.sh/m7bqH/32cc75d0c8.txt

PS: I also tested it with a .opj file which isn't customized by me, same result...

**Comment by lukespragg** [comment]
Ahh, console patching... that helps narrow it down a lot.

**Comment by neico** [comment]
I think I found the issue:  https://github.com/OxideMod/OxidePatcher/blob/master/OxidePatcher/Hooks/Simple.cs#L499

maybe logging things like that should be moved into the PatcherForm or so, or apply a global console flag to the hooks like I did on the Patcher class in #117 to avoid such problems...

**Comment by neico** [comment]
Perfect, https://github.com/OxideMod/OxidePatcher/commit/579ce977ebd98563645ab66c0774e4af63b36d90 fixed it :+1:
