### ISSUE TITLE
Class modifiers not working

### ISSUE THREAD

**Issue by Skippeh** [OxideMod/OxidePatcher#127]
For example making a private class public, inspecting the class in any decompiler will still show the class as private.

It works on other types though such as fields.

**Comment by lukespragg** [comment]
We use it and it is working, so we'd need to know more info and examples.

**Comment by Skippeh** [comment]
It seems it's only nested classes that doesn't work.

**Comment by Skippeh** [comment]
Did you verify it works? I can't get it to work on my end, I still get the same result.
