### ISSUE TITLE
Recompile code changes beyond hooks

### ISSUE THREAD

**Issue by davidmichaelhuber** [OxideMod/OxidePatcher#129]
## About

I am looking for a way to modify the patched .NET assemblies of the [Oxide Rust server](http://oxidemod.org/downloads/oxide-for-rust.1659/). Obviously OxidePatcher is able to modify the .NET assemblies (adding the line of code ```Interface.CallHook(...)```).

I actually want the hooks Oxide offers but aswell I need to make some other changes within the .NET assemblies.

## Problem

I compared the source code OxidePatcher decompiles with the one ILSpy decompiles. Both show the symbol ```c__Iterator0``` in some parts of the code where ```IEnumerators``` are used. I am not able to recompile the code decompiled with ILSpy. OxidePatcher actually is able to build the assemblies.

I tried to modify the code by adding a hook and then added some more lines of code within the "Code After" tab of OxidePather. The text area within the tab actually is read and write so I thought this might work which didn't. The added line of code simply disappeared after patching.

## Question

So is there a way I can use OxidePatcher in a way that makes it possible to also change code and add some more lines of code to the .NET assemblies?

**Comment by lukespragg** [comment]
You'd need to add the new code via IL patches. We have plans for a converter down the road, but that's an existing issue already.

**Comment by davidmichaelhuber** [comment]
> The Oxide Patcher is an IL patcher, not a builder.

Everything became clear with this sentence! Thanks a lot.
