### ISSUE TITLE
Detect if Assembly-CSharp.dll is already patched

### ISSUE THREAD

**Issue by lukespragg** [OxideMod/OxidePatcher#47]
I shouldn't be too hard to detect if the .opj file has already been applied. This would prevent the hooks becoming unflagged if you attempt to open open the GUI again, which would result in some or all of the hooks being flagged.

**Comment by HellUnit** [comment]
For this, I was thinking of possibly creating an extra element for the opj file. Something like "Patched MSIL Hash". Then generating an MSIL hash during the patch for each method patched and saving it to the opj. Then when loaded, if the MSIL hash doesn't match, it checks against the patched MSIL hash and if it matches it will notify that it has already been patched and a clean copy is needed. If neither match, it flags the method as changed. Let me know your thoughts. This is just a rough idea on how to accomplish this.

**Comment by lukespragg** [comment]
I wouldn't store anything. Just check if _Oigjnal exists and if they match.
That should be fairly quick and simple.

**Comment by HellUnit** [comment]
That is super easily doable. I'm on it.

Sent with AquaMail for Android
http://www.aqua-mail.com

**Comment by HellUnit** [comment]
Well, I've got the method for comparing the existing DLL to the 'Original' DLL (generates md5 hash byte arrays, compares their length, then their contents if the lengths match and returns a boolean to indicate if the files match), but I'm having a hard time figuring out where to call it at.

**Comment by HellUnit** [comment]
Somewhere in the VerifyProject() method in PatcherForm.cs I was thinking, but I'm at a block at the moment. I may just need some time to ponder on it.

**Comment by lukespragg** [comment]
Keep me updated as the brainstorming progresses. ;)

**Comment by HellUnit** [comment]
I've played around with a bit and the file comparison works fine. Not sure how to get it to give the functionality you want though. It already checks if *_Original exists and if it does, it uses it. If not, it creates it from the existing dll. I don't think I quite understand what the objective is here is my problem I think.

**Comment by lukespragg** [comment]
OxidePatcher will patch the DLL infinitely if you let it, as there is no check to see if the DLL was already patched. This can be an issue if you change hook settings, etc. So I'm thinking that there should be some sort of prompt to tell you that it is already patched, and then prompt to either restore the original DLL for you or allow you to do it manually.

**Comment by HellUnit** [comment]
From what I can see, it always uses *_Original.dll to patch and overwrites the base dll every time which is why you can change settings and patch repeatedly. The only time I've had an issue is when I deleted the *_Original.dll file and it created a new *_Original.dll using the patched one unless I'm missing something.

**Comment by HellUnit** [comment]
Best way I can think of around that at the moment is to create a "Last_Patched_Hash" and put it in the opj file. Then every time it tries to patch, it will check and see if the *_Original file matches the hash, meaning the *_Original has been replaced with the last patched version and it will throw up an error. If it doesn't match, it does nothing and continues as usual. Doesn't even have to be the opj file. It can be in its own file to prevent unneccesary elements in the opj.

**Comment by lukespragg** [comment]
Having using the launcher a bit more, I'm a bit unsure what to do. I believe the launcher currently uses the clean _Original.dll every time you hit patch, but I'm not sure. Can you verify?

**Comment by HellUnit** [comment]
From what I can tell, it checks if *_Original.dll exists and if it does, it uses that. If not, it creates on from *.dll. The issue would come in if you deleted *_Original.dll after patching *.dll and attempted to patch again. It would then create a *_Original.dll from the patched *.dll and you get all the hooks flagged because the MSIL hashes won't match what's in the project file anymore.

**Comment by lukespragg** [comment]
I wouldn't worry too much about this then, as it seems to work fine as long as _Original exists.
