### ISSUE TITLE
Empty class causes an error to be thrown when viewing

### ISSUE THREAD

**Issue by lukespragg** [OxideMod/OxidePatcher#62]
See attached screenshot. Happened when browsing shown class for 7 Days to Die game.

![bb1ef39a9785515cc2287291e684e870](https://cloud.githubusercontent.com/assets/671337/5892615/d1ce323c-a493-11e4-9ccd-0b593d52d3f3.png)

**Comment by HellUnit** [comment]
Possibly resolved in commit 414c9f2 . Needs testing.

**Comment by lukespragg** [comment]
Appears to be working fine, thanks!

![76d487d7104d5c9bba6d9b9cf05c5673](https://cloud.githubusercontent.com/assets/671337/6273489/c494f340-b83d-11e4-8801-d4d2ff9504d9.png)
