### ISSUE TITLE
"Press Enter to continue" message improvement

### ISSUE THREAD

**Issue by lukespragg** [OxideMod/OxidePatcher#64]
Right now I have a batch script setup that I test with sometimes, and I usually use a "pause" at the end. This results in a duplicate message, which I'm not really sure is avoidable when using it via this method. However, would it make more sense to accept any input like how "pause" shows?

![6a513a8c383ee26352e478342314cf1f](https://cloud.githubusercontent.com/assets/671337/5906140/5d095e74-a563-11e4-8381-1f9800712854.png)

**Comment by HellUnit** [comment]
Accepting input in the console is a whole other can of worms compared to 
simply displaying it when it comes to WinForm applications. I'll look into 
it at some point, but for the trivial nature of the issue, probably more 
trouble than its worth.

Sent with AquaMail for Android
http://www.aqua-mail.com

**Comment by lukespragg** [comment]
Probably so, it was just a thought.

**Comment by HellUnit** [comment]
Could remove the message altogether. It seems to exit properly when run via batch script. When I was running it manually in a console, it doesn't exit to the command prompt until you press enter. I couldn't figure out why it does that, but I just put the message there to indicate the program was finished and you needed to hit enter to get the prompt back.

**Comment by HellUnit** [comment]
As a side note, it seemed to only work with Enter or Ctrl-C (break). I think I tried other keys and it didn't do anything.

**Comment by HellUnit** [comment]
I even tried "detaching" the process from the console and forcing Environment.Exit(); but neither seem to have had an effect. It won't return to the prompt unless enter or break are pressed. A consequence of a WinForms app running as console, I believe. Most information I looked up advises to create to different executables, one for each specific purpose, but that isn't really necessary for the functionality we need to achieve with it.

**Comment by lukespragg** [comment]
Yeah, not really a big issue either way.
