### ISSUE TITLE
Tab order of form fields/buttons is incorrect

### ISSUE THREAD

**Issue by lukespragg** [OxideMod/OxidePatcher#80]
Hitting tab should move through the fields and buttons from top to bottom, then left to right, but instead it jumps between them incorrectly.

**Comment by Mughisi** [comment]
Wasn't this corrected at some point? Using tab seems to do this or am I missing something?

**Comment by lukespragg** [comment]
I think I fixed some of it, but I think some is still off.

**Comment by HellUnit** [comment]
On September 4, 2015 4:05:53 PM EDT, Luke Spragg <notifications@github.com> wrote:
>I think I fixed some of it, but I think some is still off.
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/OxideMod/OxidePatcher/issues/80#issuecomment-137841609

The only issue I remember having is that some of the tabs have fields or buttons that are created at runtime and I couldn't figure out how to dynamically change the tab order once the buttons/fields were created. I'm sure it can be done though.
-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by lukespragg** [comment]
See https://github.com/OxideMod/OxidePatcher/commit/8e5a9e5ecbb65081da89b87b7b34b60b6650c21a.
