### ISSUE TITLE
NullReferenceException when right-clicking on methods in DLL

### ISSUE THREAD

**Issue by lukespragg** [OxideMod/OxidePatcher#97]
![51a53414264e18e4a2a3ad8783deaba0](https://cloud.githubusercontent.com/assets/671337/10294710/0131f4d8-6b8a-11e5-9bb8-59c069dd78dc.png)

**Comment by HellUnit** [comment]
Sorry for disappearing for a while. I recently started going back to school, so my free time has been limited. Back on topic, is this a Rust DLL or from another game? If it is Rust, which DLL in particular? If it is not Rust, I'll probably need a copy of the DLL that caused it so I can trace it down and add some error handling.

**Comment by lukespragg** [comment]
It can be from pretty much any game, but in this case it was Rust.

![eb463cf1e4422c3a04d009333f4c062f](https://cloud.githubusercontent.com/assets/671337/10594446/3e7e1a12-769b-11e5-950f-d27e9022e365.png)

**Comment by HellUnit** [comment]
On October 19, 2015 7:54:45 PM EDT, Luke Spragg <notifications@github.com> wrote:
>It can be from pretty much any game, but in this case it was Rust.
>
>![eb463cf1e4422c3a04d009333f4c062f](https://cloud.githubusercontent.com/assets/671337/10594446/3e7e1a12-769b-11e5-950f-d27e9022e365.png)
>
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/OxideMod/OxidePatcher/issues/97#issuecomment-149379556

Gotcha. I'll take a look when I have a moment and see what I can do.
-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by Mughisi** [comment]
Completely forgot about this one, I'm like 99% sure of what is causing it, I'll check it when I get home today.
